apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-spring-nexus
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
  - host: edu00-spring.duckdns.org
    http:
      paths:
      - backend:
          service:
            name: hello-spring-svc
            port:
              number: 80
        path: /
        pathType: Prefix
